VirtualPT_WebApp/VirtualPT/config/routes.rb
VirtualPT::Application.routes.draw do
  get "schedule_exercises/index"

  resources :users
  resources :exercises
  resources :schedules do
    post :schedule, on: :collection
    
  end

  

end

VirtualPT_WebApp/VirtualPT/app/models/exercise.rb
class Exercise < ActiveRecord::Base
	include ModelModule

	has_and_belongs_to_many :schedules


	def self.parseAll
		return ModelModule.fetchObjects('Exercise')
	end
end

VirtualPT_WebApp/VirtualPT/app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

VirtualPT_WebApp/VirtualPT/app/models/schedule.rb
class Schedule < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :exercises
	
	def username
		@username
	end

	def username=(username)
		@username = username
	end
end

VirtualPT_WebApp/VirtualPT/app/models/test.rb
# include ModelModule
require 'json'
string = %Q|{"results":[{"profile":{"__type":"Pointer","className":"Profile","objectId":"hkJIqkIPlw"},"email":"yang@stanford.edu","username":"yang","createdAt":"2014-05-11T18:12:23.554Z","updatedAt":"2014-05-11T18:12:39.834Z","objectId":"O9MmEreORk"},{"profile":null,"username":"eV90K8MvjK2FZhCqRzgLyatfB","createdAt":"2014-05-11T20:00:19.665Z","updatedAt":"2014-05-11T20:00:19.890Z","objectId":"mmoRpN3qDw"},{"username":"gwen","email":"gwen@stanford.edu","profile":{"__type":"Pointer","className":"Profile","objectId":"null"},"createdAt":"2014-05-12T07:08:32.675Z","updatedAt":"2014-05-12T07:08:32.675Z","objectId":"TSTBRJnYrK"},{"username":"gw2en","email":"gwen@stanfor2d.edu","profile":null,"createdAt":"2014-05-12T07:17:30.666Z","updatedAt":"2014-05-12T07:17:30.666Z","objectId":"gVFQLpsjrv"},{"username":"yang2","email":"christine@stanford.edu","profile":{"__type":"Pointer","className":"Profile","objectId":"null"},"createdAt":"2014-05-12T07:21:58.501Z","updatedAt":"2014-05-12T07:21:58.501Z","objectId":"NU40luPTtp"},{"username":"2323","email":"christine@stan2ford.edu","createdAt":"2014-05-12T07:22:54.215Z","updatedAt":"2014-05-12T07:22:54.215Z","objectId":"AocVHBdqD8"}]}
|;
parsed =  JSON.parse(string)
users = Array.new

parsed["results"].each do |user|
	users << user["username"]
end

puts users

VirtualPT_WebApp/VirtualPT/app/models/user.rb
class User < ActiveRecord::Base
	include ModelModule
	 # no validations included, but feel free to add your own
  	validates_presence_of :username

  	has_one :profile
  	has_many :schedules


  def self.parseAll
  	return ModelModule.fetchUsers()
  end
  
end

VirtualPT_WebApp/VirtualPT/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # helper_method :parseHeader
  # helper_method :parseDomain
  # helper_method :createObject

require 'net/http'
require 'net/https'

  def parseHeader
    {
       "X-Parse-Application-Id" => "L6SLBxrQtNVjvdO8TCaYH7rpMHStR832rJoTloW0",
       "X-Parse-REST-API-Key"=> "zqZskYHskGj6R2eMxBBS7Q4b6eUJ09VJHYVgKrXR",
       "Content-Type" =>"application/json"
    }
  end
  
  def parseDomain(ext)
    "https://api.parse.com/1/#{ext}"
  end
 
  def constructObjectPostRequest(objectType)
	uri = URI.parse(parseDomain("classes/#{objectType}"))
	# uri = URI.parse("https://api.parse.com/1/classes/MyObject")
	https = Net::HTTP.new(uri.host,uri.port)
	https.use_ssl = true  	
	req = Net::HTTP::Post.new(uri.path, nitheader = parseHeader)
	return https, req
  end

 
  def constructUserPostRequest()
	uri = URI.parse(parseDomain("users"))
	# uri = URI.parse("https://api.parse.com/1/classes/MyObject")
	https = Net::HTTP.new(uri.host,uri.port)
	https.use_ssl = true
	req = Net::HTTP::Post.new(uri.path, nitheader = parseHeader)
	return https, req
  end

# TODO: DRY -- reuse more code
  def constructUserGetRequest()
  	uri = URI.parse(parseDomain("users"))
	# uri = URI.parse("https://api.parse.com/1/classes/MyObject")
	https = Net::HTTP.new(uri.host,uri.port)
	https.use_ssl = true
	req = Net::HTTP::Get.new(uri.path, nitheader = parseHeader)
	return https, req
end


 def createObject(objectType, objectData)
    https, req = constructObjectPostRequest(objectType)
    req.body = objectData.to_json
    res = https.request(req)
    puts res.body
    return res.is_a?(Net::HTTPSuccess), res.body

    # puts parseDomain("classes/#{objectType}");
    # Nestful.post parseDomain("classes/#{objectType}"), :format => :json, :headers => parseHeader, :params => objectData
    
    # Nestful::Request.new("https://api.parse.com/1/Object2", :method => :post, :params => objectData, :headers => parseHeader, :format => :json).execute
  end

  def createUser(userData)
  	https, req = constructUserPostRequest()
  	req.body = userData.to_json
  	res = https.request(req)
  	puts res.body
    puts ">>>>>>>>>>>>>>response status**********"
    puts res.is_a?(Net::HTTPSuccess)
  	return res.is_a?(Net::HTTPSuccess), res.body
  end


end

VirtualPT_WebApp/VirtualPT/app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def index
		 @exercises = Exercise.parseAll
	end
end

VirtualPT_WebApp/VirtualPT/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  require 'Date'
  
  def index	
	@users = User.parseAll
	@exercises = Exercise.parseAll
	@schedule = Schedule.new



	# @results = createObject('Yaoy2aoObject', {
 #      "foo2" => "bar"
 #    })

	# @user = createUser({
	# 	"username" => "gw2en",
	# 	"password" => "123",
	# 	"email" => "gwen@stanfor2d.edu",
	# 	"profile" => nil
	# 	# "profile" => {
 # 	# 					 "__type" => "Pointer",
 # 	# 					 # "className" => "Profile",
 #  # 						#  "objectId" => "null"
	# 	# 			  }
	# 	})
	# profile_query = Parse::Query.new("Profile")
	# profile_query.get

	# puts profile_query
  end


  def new
    @users = User.parseAll
    @exercises = Exercise.parseAll
    @schedule = Schedule.new
  end

  def schedule
    date = params[:schedule][:date].split('/')
    date_str = DateTime.new(date[2].to_i, date[0].to_i, date[1].to_i)
  	
    success, message = createObject("Schedule", {
  		"date" => {
                "__type" => "Date",
                "iso" => date_str
                },
  		"user" => {
  					"__type" => "Pointer",  
  					"className" => "_User",
  					"objectId" => params[:schedule][:username]
  				  },
  		"exercise" => {
  					"__type" => "Pointer",
  					"className" => "Exercise",
  					"objectId" => params[:schedule][:exercise]
  				  },
      "reps" => params[:schedule][:reps].to_i,
      "duration" => params[:schedule][:duration].to_i,
      "hold" => params[:schedule][:hold].to_i,
      "sets" => params[:schedule][:sets].to_i
  		})
    
     if (success) 
      flash[:notice] = "New exercise successfully added to schedule! " + message
    else
      flash[:notice] = message  
    end
    redirect_to new_schedule_path
  end


  private
  def schedule_params
  	params.permit(:username, :date, :exercise, :reps, :duration, :hold, :sets)
  end

end

VirtualPT_WebApp/VirtualPT/app/helpers/application_helper.rb
module ApplicationHelper
end

VirtualPT_WebApp/VirtualPT/app/helpers/exercises_helper.rb
module ExercisesHelper
end

VirtualPT_WebApp/VirtualPT/app/helpers/schedules_helper.rb
module SchedulesHelper
end

VirtualPT_WebApp/VirtualPT/app/views/exercises/index.html.erb
<h1>Exercise Library</h1>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th style="width: 18%">Exercise Name</th>
    <th>Instruction</th>
    <th>Duration</th>
    <th>Hold</th>
    <th>Reps</th>
    <th>Image URL</th>
    <th>Video URL</th>
  </tr>
 
  <% @exercises.each do |exercise| %>
    <tr>
      <td><%= exercise["name"].downcase.capitalize %></td>
      <td><%= exercise["instruction"].downcase.capitalize %></td>
	  <td><%= exercise["duration"] %></td>
	  <td><%= exercise["hold"] %></td>
  	  <td><%= exercise["reps"] %></td>
  	  <td><%= exercise["imgURL"] %></td>
  	  <td><%= exercise["videoURL"] %></td>
    </tr>
  <% end %>
</table>

VirtualPT_WebApp/VirtualPT/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VirtualPT" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">VirtualPT</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Exercise Library", exercises_path  %></li>
              <li><%= link_to "Schedule Exercise", new_schedule_path  %></li>
              <li><%= link_to "Help", "#"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Navigator</li>
              <li><%= link_to "Exercise Library", exercises_path  %></li>
              <li><%= link_to "Schedule Exercise", new_schedule_path  %></li>
              <li><%= link_to "Parse Server", "https://www.parse.com/apps/virtualpt/collections" %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; VirtualPT 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

VirtualPT_WebApp/VirtualPT/app/views/schedules/index.html.erb
<p> Please schedule the Exercise Using following forms </p>


<div>
<%= form_for @schedule, url: schedule_schedules_path, :class => "form-inline"  do |f| %>   
<!-- 
	<div class="row">
 		<label>User Name </label>
  		<label>Date</label>
  		<label>Exercise </label>
	</div> -->

<div id="form-panel">
    <div class="exercise-item">

    <% users_array = @users.map {|user| [user["username"], user["objectId"]]} %>
    <% exercises_array = @exercises.map {|exercise| [exercise["name"].downcase.capitalize, exercise["objectId"]]} %>
    
    <%= f.select :username, users_array %>
    <%= f.text_field :date, :placeholder => "Date" %>
    <%= f.select :exercise, exercises_array %>
    		<button type="button" class="btn btn-primary">Remove</button>
    	<!-- </div> -->
    </div>

</div>

 <div>
 	<button type="button" class="btn btn-primary"  id="add_item">Add Exercise</button>
 	<%= f.submit "Schedule", :class => "btn btn-primary" %>
 </div>

<% end %>


</div>

</div>



<script type="text/javascript">
$('#schedule_date').datepicker();
$('#add_item').click(function(){
	$('#form-panel').append($(".exercise-item").html());
});

</script>
<!-- <script type="text/javascript" src="http://www.parsecdn.com/js/parse-1.2.18.min.js"></script> -->
<!--<script type="text/javascript"> 
    // Parse.initialize("L6SLBxrQtNVjvdO8TCaYH7rpMHStR832rJoTloW0", "CN9wifxib3XPrtM7HZVPSSjKifejQSRyJftj0g3n");
    
    // Parse.User.signUp("yangyang5", "123", {email:"yyy@email.com"});


 //    console.log(newUser);
 //    newUser.setUsername("yangyang");
 //    newUser.setEmail("yzhao3@stanford.edu");
 //    newUser.save({username:"yangyang"}).then(function(object) {
 //    alert("yay! it worked");
	// });


    // var TestObject = Parse.Object.extend("TestObject");
    // var testObject = new TestObject();
    //   testObject.save({foo: "bar"}, {
    //   success: function(object) {
    //     $(".success").show();
    //   },
    //   error: function(model, error) {
    //     $(".error").show();
    //   }
    // });


//     var TestObject = Parse.Object.extend("TestObject");
//     var testObject = new TestObject();
//     testObject.save({foo: "bar"}).then(function(object) {
//     alert("yay! it worked");
// });
  
</script> -->

VirtualPT_WebApp/VirtualPT/app/views/schedules/new.html.erb
<h1>Schedule Panel</h1>

<p> Please schedule the Exercise Using following forms </p>


<div>
<%= form_for @schedule, url: schedule_schedules_path, :class => "form-inline"  do |f| %>   

<div id="form-panel">

    <div class="exercise-item">

    <% users_array = @users.map {|user| [user["username"], user["objectId"]]} %>
    <% exercises_array = @exercises.map {|exercise| [exercise["name"].downcase.capitalize, exercise["objectId"]]} %>
    
    <%= f.select :username, users_array %>
    <%= f.select :exercise, exercises_array %>
    <br>
    <%= f.text_field :date, :placeholder => "Date", :style=>"width: 120px" %>
    <%= f.text_field :reps, :placeholder => "Reps", :style=>"width: 120px"  %>
    <%= f.text_field :hold, :placeholder => "Hold(seconds)", :style=>"width: 120px"  %>
    <%= f.text_field :duration, :placeholder => "Duration(seconds/Set)", :style=>"width: 120px" %>
    <%= f.text_field :sets, :placeholder => "Sets #", :style=>"width: 120px"  %>
    </div>
</div>

 <div>
 	<%= f.submit "Add Exercise", :class => "btn btn-primary" %>
 </div>

<% end %>
</div>

</div>



<script type="text/javascript">
$('#schedule_date').datepicker();
// $('#add_item').click(function(){
// 	$('#form-panel').append($(".exercise-item").html());
// });

</script>

VirtualPT_WebApp/VirtualPT/app/views/schedules/schedule.html.erb
<h1>Schedules</h1>